package pl.dev.bkwiatkowski.common.permission

enum class AppPermission {
  CAMERA,
  GALLERY,
  STORAGE,
  WRITE_STORAGE,
  LOCATION,
  COARSE_LOCATION,
  BACKGROUND_LOCATION,
  BLUETOOTH_LE,
  REMOTE_NOTIFICATION,
  RECORD_AUDIO,
  BLUETOOTH_SCAN,
  BLUETOOTH_ADVERTISE,
  BLUETOOTH_CONNECT,
  CONTACTS,
  MOTION,
}